name: copy files
on: [push]
jobs:

  build:
    name: copy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "https://iptv-org.github.io/iptv/index.country.m3u"
        target: "iptv-a.txt"
